name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          driver-opts: |
            image=moby/buildkit:v0.27.0
          

      - name: Login to Artifactory (HTTP)
        run: |
          docker login https://mill.jfrog.info:12451 \
            -u ${{ secrets.DOCKER_USERNAME }} \
            -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile 
          push: true
          tags: https://mill.jfrog.info:12451/test-docker/demo-app:latest
          platforms: linux/amd64,linux/arm64
         
         
     
          
