name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          driver-opts: |
            image=moby/buildkit:v0.27.0
          buildkitd-config-inline: |
            [registry."support-team-akshathap-arti.jfrog.farm:8081"]
              http = true
              insecure = true
          
      - name: Insecure Docker Repository
        run: |
          sudo tee /etc/docker/daemon.json <<EOF
          {
           "insecure-registries": ["support-team-akshathap-arti.jfrog.farm:8081"]
          }
          EOF
          sudo systemctl restart docker

      - name: Login to Artifactory (HTTP)
        run: |
          docker login http://support-team-akshathap-arti.jfrog.farm:8081 \
            -u ${{ secrets.DOCKER_USERNAME }} \
            -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile 
          push: true
          tags: support-team-akshathap-arti.jfrog.farm:8081/test-docker/demo-app:latest
          platforms: linux/amd64,linux/arm64
          extra-args: --insecure
         
     
          
